[package]
name = "ffmpeg_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
arboard = "3.4.0"
eframe = "0.27"
parking_lot = "0.12.3"
rfd = "0.14"
serde = { version = "1.0", features = ["derive"] }

[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
